print("hello friend 1 when is ur b-day?")
birthday1=input()
print("hello friend 2 when is ur b-day?")
birthday2=input()
print("hello friend 3 when is ur b-day?")
birthday3=input()
print("hello friend 4 when is ur b-day?")
birthday4=input()
print("hello friend 5 when is ur b-day?")
birthday5=input()
print("friend one b-day is",birthday1 )
print("friend two b-day is",birthday2 )
print("friend three b-day is",birthday3 )
print("friend four b-day is",birthday4 )
print("friend five b-day is",birthday5 )
